version: '3.3'

services:
  db:
    image: "postgres:13"
    container_name: ${PROJECT_NAME}PostgresDatabase
    environment:
      - POSTGRES_DB=news
      - POSTGRES_USER=news_admin
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: ${PROJECT_NAME}Web
    environment:
      DJANGO_SETTINGS_FOLDER: Test_Task
    depends_on:
      - db
    ports:
      - "8080:8080"

#  nginx:
#    image: nginx
#    container_name: ${PROJECT_NAME}Nginx
#    ports:
#      - "8250:80"
#    depends_on:
#      - web
